            - name: Swift DocC Action
  # You may pin to the exact commit or the version.
  # uses: fwcd/swift-docc-action@3c0d98e9eb344aa66952020b4cecda0eb8b69858
  uses: fwcd/swift-docc-action@v1.0.2
  with:
    # The target to document.
    target: # optional
    # The output folder.
    output: # optional
    # The path at which the docs will be hosted.
    hosting-base-path: # optional
    # Whether to disable indexing.
    disable-indexing: # optional
    # Whether to generate documentation suitable for static hosting (e.g. on GitHub Pages).
    transform-for-static-hosting: # optional
          
