name: DocC
on:
  push:
    branches:
      - '**'
jobs:
  build_docC:
    runs-on: macos-12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: checkout
      uses: actions/checkout@v3
      with:
       repository: ${{ github.event.pull_request.head.repo.full_name }}
       ref: ${{ github.event.pull_request.head.ref }}

    - name: build static site
      uses: kiarashvosough1999/build-docC-static-site@v1.0.2
      
  build_deploy_site:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      contents: read
      id-token: write

    steps:
     - name: Deploy DocC To Github-Pages
       uses: kiarashvosough1999/docC-github-pages-deploy@v1.0.0
         
