            - name: Deploy DocC To Github-Pages
  # You may pin to the exact commit or the version.
  # uses: kiarashvosough1999/docC-github-pages-deploy@ab7ea8fb02596a4f2ae75e8d411396b6e07a255b
  uses: kiarashvosough1999/docC-github-pages-deploy@v1.0.0
  with:
    # The name of the ziped artifact which was uploaded on previous steps.(artifact must be zipped with .tar extension only)
    docC-generated-static-site-uploaded-name: # default is docC_generated_site_zipped
          
