name: DocC
on:
  push:
    branches:
      - '**'
jobs:
  build_deploy_site:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      contents: read
      id-token: write

    steps:
     - name: Swift DocC Action
       uses: fwcd/swift-docc-action@v1.0.2
